### ISSUE TITLE
BuildVision Seizes Focus from VS Test Explorer

### ISSUE THREAD

**Issue by jzabroski** [StefanKert/BuildVision#101]
@StefanKert I am not an expert in VS IDE Plug-in development, but my basic observation is that when I run a test in Visual Studio, if BuildVision and Test Explorer are in the same tab pane together, BuildVision will steal focus, and when the build succeeds, it does not reflow focus to the Test Explorer or previously focused tab in the tab pane its colocated with.

**Comment by StefanKert** [comment]
Hi there :)

can you provide a screenshot of your setup? Is this happening with other Tool Windows as well or only the VS Test Explorer?

**Comment by jzabroski** [comment]
Hi @StefanKert , thanks for your patience.  Had 3 day weekend in US.

It seems like there are a couple of things I notice.

1. When BuildVision is not focused and Output window is focused, BuildVision permanently says Cancel, even after the Build completed without errors.  Clicking Cancel also does nothing, since the Build is completed.  I confirmed the Build is completed by checking the Output window and seeing, "========== Build: 36 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
".  Additionally, I checked the Error List window and see there were no build errors indicating the Visual Studio process ran out of memory during the build.  (This is an easy screenshot to take because nothing proprietary is on the screen.)
![image](https://user-images.githubusercontent.com/447485/86624589-8faf1280-bf91-11ea-9956-4d2768a0b9b8.png)
2. Upon clicking Rebuild Solution, with BuildVision focused, the Output window takes focus.
3. Upon using JetBrains ReSharper's "Run All Tests From Solution", JetBrains seems to take focus after an Incremental Build (which is correct behavior).
4. Upon using Visual Studio Test Explorer (built-in to Visual Studio), it appears VS Text Explorer does not regain focus.

Perhaps this is a problem with VS Text Explorer that JetBrains solves for us.

### Additional Info
I have verified I am using 3.0.0.104 (you can also see the git commit hash on the other screen shot).
![image](https://user-images.githubusercontent.com/447485/86625032-68a51080-bf92-11ea-9c80-f5574d7834c9.png)

**Comment by StefanKert** [comment]
Thanks for the detailed infos :)

I´ll take a look asap at these issues and keep you updated :)
