### ISSUE TITLE
BuildVision is always closed on VS startup

### ISSUE THREAD

**Issue by bishopnator** [StefanKert/BuildVision#103]
Previously the BuildVision window state was saved and after opening VS it was restored properly (it is shown if last time it was shown when VS was closed). Now in version 3.01 the window must be always manually opened after the VS is started.

**Comment by StefanKert** [comment]
Thanks for bringing this up. Seems like while fixing #93 I removed the logic for keeping BuildVision up. I´ll try to bring up a fix asap.

**Comment by NPadrutt** [comment]
Is there an update to this issue? :)

**Comment by StefanKert** [comment]
Hi folks :)

sorry for the delay. I just released 3.0.2  which contains the fix :)
