### ISSUE TITLE
View has to be opened once manually on startup

### ISSUE THREAD

**Issue by NPadrutt** [StefanKert/BuildVision#109]
First of all, thanks for your work. I really appreciate this extension!

The one issue I have, is that everytime when I open a solution I have to first open the BuildVision tab manually,  otherwise it won't open automatically on a build.  All of my views like the Error View, Output, etc. are minimized per default, to have as much real estate for my code view as possible - especially on a laptop. But it seems to work correctly when I pin it so that it is always open. And it does corretly open up as soon as I once opened it.

**Comment by StefanKert** [comment]
Hi @NPadrutt, I believe that this should be fixed with 4.0.0. If not please reopen :)
