### ISSUE TITLE
VisualStudio 2022 support

### ISSUE THREAD

**Issue by D0ctorWh0** [StefanKert/BuildVision#112]
Can this extension be updated to support Visual Studio 2022?

**Comment by AgWillow** [comment]
Please do.
[_Devoted fan_]

**Comment by willl** [comment]
Here's a [VS 2022 extension upgrade guide](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022) if anyone wants to give it a go. Not sure how much work would be involved for the upgrade. 

VS 2019 support was also a community contribution https://github.com/StefanKert/BuildVision/pull/69

**Comment by StefanKert** [comment]
Hi folks,

currently giving it a shot. I will try to publish a version that works with 2022 today.

**Comment by StefanKert** [comment]
So after a quick investigation it looks like the upgrade is a bit tricky, since some of the events that have been used aren't available anymore in VS 2022. I'll take a look at this in the next days and keep you updated.

**Comment by StefanKert** [comment]
Just pushed a preview to the [VSIX Gallery - BuildVision](https://www.vsixgallery.com/extension/837c3c3b-8382-4839-9c9a-807b758a929f). Currently there is a known issue with showing build errors. Somehow the hook-in point for MSBuild is not available anymore, but I'll check that in the next days. Any feedback is greatly appreciated. If you have troubles setting up the VSIX Gallery in VS checkout this guide https://github.com/StefanKert/BuildVision#preview-builds-for-buildvision

Have fun :)

**Comment by roalz** [comment]
I've installed the 3.1.0.2 preview above on both VS2019 and VS2022, so far I have not seen any problem,
except (as you wrote) for the lack of errors details under a failing project in VS2022 (still working fine in VS2019).

**Comment by Pursche** [comment]
I'm a huge fan of this extension. I've tried the 3.1.0.2 preview on VS2022 and other than the mentioned lack of errors the only "issue" I'm having is that successful builds are showing up as UpToDate.

**Comment by StefanKert** [comment]
Just published the latest preview version to the Feed that should fix the missing error details. [3.1.0.3](https://www.vsixgallery.com/extension/837c3c3b-8382-4839-9c9a-807b758a929f)

@Pursche looks like this issue is reproducible for me I'll try to include it in the next preview that will be the final preview before release.

**Comment by StefanKert** [comment]
🎉 🎉 🎉 🎉 v3.1.0 with VS 2022 support has just been pushed to the Marketplace. Thank you very much for all the comments and the feedback for the previews :). If anyone is facing any issues with the news version please open another issue :)
