### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by gnimor** [StefanKert/BuildVision#119]
When opening the BuildVision window, there is a progress bar in the upper area. Nevertheless, building a solution with multiple projects does not change the progress bar (stays on 0%).

**Comment by StefanKert** [comment]
Hi there,

a Preview of version 4.x is available in the VSIX Gallery feed.  You can follow along with the installation instructions from the README https://github.com/StefanKert/BuildVision?tab=readme-ov-file#setup-visual-studio-for-preview-channel. Would love to hear if this fixes the issues you are facing. As soon as the issues that people are currently seeing are resolved there will be a official marketplace release.

Thanks :)

**Comment by StefanKert** [comment]
There has been an issue with the calculation. This should be fixed with the latest version.
