### ISSUE TITLE
screen keeps dying

### ISSUE THREAD

**Issue by hweight** [StefanKert/BuildVision#12]
HI.. i have been using build vision on VS 2012 and 2013, and at random times, the interface for build vision dies.  when it dies, it takes the error list and output tabs as well, so they appear the same as well. 
Sometimes build vision comes back to normal, but that is after a random number of builds. in some cases, will need to exit VS and restart it to see anything in that panel (ie, errors). 

![buidvision dying](https://cloud.githubusercontent.com/assets/13824962/9296401/eab05d72-44be-11e5-8c7a-39c9e3a700d3.JPG)

**Comment by igorushi** [comment]
Hi have similar issue in VS2015:
![image](https://cloud.githubusercontent.com/assets/7131092/9301141/e61385c6-44d4-11e5-9bef-b331d20ec557.png)

**Comment by StefanKert** [comment]
Is this still an issue? If so please let me know.

**Comment by igorushi** [comment]
I didn't faced with it last year ...

**Comment by StefanKert** [comment]
Ok. I am closing this issue for now. If this issue pops up again please reopen.
