### ISSUE TITLE
Create a `main` branch.

### ISSUE THREAD

**Issue by tacosontitan** [StefanKert/BuildVision#124]
Back in 2020, GitHub began making efforts to move away from `master` as the primary branch in repositories. Instead, the default for new repositories is `main` and many established repositories have already made the switch. It is recommended to change the primary branch name from `master` to `main` to keep in line with the current industry standard.

<sub>*This is by no means a critical thing, I just noticed it and figured I would point it out.*</sub>

**Comment by tacosontitan** [comment]
If this idea was adopted by this repository, another issue should likely be created to remove the `master` branch.

**Comment by tacosontitan** [comment]
For additional information see the [GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch).

**Comment by StefanKert** [comment]
Thanks for the hint :) updated
