### ISSUE TITLE
Unable to load package

### ISSUE THREAD

**Issue by ankit-mishra-mt** [StefanKert/BuildVision#127]
Got below error on launching VS 2022 as well as VS 2022 Preview
BuildVision Version: 3.1.0
![image](https://github.com/StefanKert/BuildVision/assets/98411212/1722f487-e7bb-4ced-b59f-25a3a7c915ef)

<description>SetSite failed for package [BuildVisionPackage]Source: &apos;Microsoft.VisualStudio.Validation&apos; Description: Cannot find an instance of the Microsoft.VisualStudio.Shell.Interop.IVsSolutionBuildManager5 service.&#x000D;&#x000A;</description>

**Comment by AgWillow** [comment]
Isn't this the same issue reported in issue #120?

**Comment by mishra-ankit-learn** [comment]
Thanks for pointing me to the thread. I'll follow that and will close this issue as duplicate

**Comment by ankit-mishra-mt** [comment]
Duplicate of #120
