### ISSUE TITLE
Long multi-line error messages get truncated

### ISSUE THREAD

**Issue by igorushi** [StefanKert/BuildVision#13]
A picture is worth a 1000 words :)
![image](https://cloud.githubusercontent.com/assets/7131092/10108990/db2bd1b0-63cc-11e5-99bd-d26391eb67d4.png)

This is how it looks in a VS error list :
![image](https://cloud.githubusercontent.com/assets/7131092/10109090/83de3fb4-63cd-11e5-8c8f-77ab069b615c.png)

**Comment by StefanKert** [comment]
Seems like we´ve got a problem with a max-height in the errors grid. I was able to reproduce it:

![image](https://user-images.githubusercontent.com/7176615/27435234-cea8222a-575b-11e7-886e-88c61f9d6624.png)
 
I will take a look at it asap.

**Comment by StefanKert** [comment]
Just released ah new version that should handle long error messages better. [1.4.1.60](https://github.com/StefanKert/BuildVision/releases/tag/v1.4.1.60)

Please let me know if this fits your needs. Right now a scrollbar is added to scroll through the issue.

**Comment by igorushi** [comment]
@StefanKert , cool thank you!
