### ISSUE TITLE
Visual Studio 15 support

### ISSUE THREAD

**Issue by xperiandri** [StefanKert/BuildVision#17]

**Comment by xperiandri** [comment]
Basically it is enough to increase allowed version in `extension.vsixmanifest`

**Comment by xperiandri** [comment]
``` XML
    <SupportedProducts>
      <VisualStudio Version="11.0">
        <Edition>Ultimate</Edition>
        <Edition>Premium</Edition>
        <Edition>Pro</Edition>
      </VisualStudio>
      <VisualStudio Version="12.0">
        <Edition>Ultimate</Edition>
        <Edition>Premium</Edition>
        <Edition>Pro</Edition>
      </VisualStudio>
      <VisualStudio Version="14.0">
        <Edition>Enterprise</Edition>
        <Edition>Pro</Edition>
        <Edition>Community</Edition>
      </VisualStudio>
      <VisualStudio Version="15.0">
        <Edition>Enterprise</Edition>
        <Edition>Pro</Edition>
        <Edition>Community</Edition>
      </VisualStudio>
    </SupportedProducts>
```

**Comment by dsoronda** [comment]
+1 for VS 2017

**Comment by xperiandri** [comment]
Actually it throws lots of exceptions.
So it requires modification for VS 2017

**Comment by sergey-tihon** [comment]
👍 plz plz plz 👍

**Comment by roalz** [comment]
Would it make sense to change the title to "Visual Studio 2017 support", now that VS2017 is out?

+1MILLION for VS 2017 support, anyway ;-)

**Comment by calloncampbell** [comment]
+1 for VS2017 support please.

**Comment by StefanKert** [comment]
Created a fork and added support for VS 2017:

[https://github.com/StefanKert/BuildVision/releases](https://github.com/StefanKert/BuildVision/releases)

Will get in touch with the repo maintainer. Probably we can fix something to get this repo maintained again ;) 

Greets

**Comment by roalz** [comment]
Great Stefan! It would be great to keep this repo alive and maintained again, with "official" updates to the VS MarketPlace as well.

**Comment by StefanKert** [comment]
Yeah. Fairly busy today. I will get in touch with maintainer of the repo asap, so we can push the package to VS Marketplace.

**Comment by roalz** [comment]
No worries, we are all busy (more or less), take your time.
It's already great to have a release package supporting VS2017! Thanks

**Comment by StefanKert** [comment]
@roalz Just a little update. I contacted @nagits on this case via mail, but haven´t gotten a response yet. Stil waiting. Stay tuned for updates.

**Comment by StefanKert** [comment]
Like mentioned in #21 we´ve released a version that should work with VS 2017 and should have some minor improvements. We´ve restructured the project and changed many things. Since this issue is targeting VS 2017 (15) I´m closing this now and wanted to ask you that we really like to ask you if you´ve got some time to test the [Current Pre-Release](https://github.com/StefanKert/BuildVision/releases/tag/v1.4.0.57) and give some feedback on it. Really appreciate any kind of feedback! If any problems with this version occure please open another issu.e

**Comment by xperiandri** [comment]
Cool! Installing!
