### ISSUE TITLE
Extension prevents output window to show in VS 15

### ISSUE THREAD

**Issue by Janek91** [StefanKert/BuildVision#19]
When installed in Visual Studio 2015 - Output window is prevented from show up. Because of that it's impossible i.e. to add new item to project. Only workaround I've found to fix it, is to disable extension.

**Comment by roalz** [comment]
Please change the title, it may confuse between VS 2015 and VS "15" (now VS 2017)

**Comment by StefanKert** [comment]
@Janek91 Is this still relevant? Are you still facing issues with BuildVision. Please let me know.

**Comment by StefanKert** [comment]
Since there is no feedback given I will close this for now. If you´re still facing this issue please feel free to reopen.
