### ISSUE TITLE
Pre-release vsix 1.4.0.57 - error when installting

### ISSUE THREAD

**Issue by jbaute** [StefanKert/BuildVision#24]
Tried the new VS2017 pre-release and it's failing with the error message: 
> This extension is not installable on any currently installed products.

I'm seeing this in the install log:

> 22/06/2017 17:16:36 - Searching for applicable products...
> 22/06/2017 17:16:36 - Found installed product - Microsoft Visual Studio Enterprise 2015
> 22/06/2017 17:16:36 - Found installed product - Microsoft Visual Studio Professional 2015
> 22/06/2017 17:16:36 - Found installed product - Microsoft Visual Studio Community 2015
> 22/06/2017 17:16:36 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
> 22/06/2017 17:16:36 - Found installed product - Global Location
> 22/06/2017 17:16:36 - Found installed product - Visual Studio Enterprise 2017
> 22/06/2017 17:16:39 - System.ArgumentNullException: Value cannot be null.
> Parameter name: String
>    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>    at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
>    at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
>    at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
>    at VSIXInstaller.SupportedVSSKU.get_Host()
>    at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at System.Lazy`1.get_Value()
>    at VSIXInstaller.App.GetExtensionEngineForApplicableSKU(SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
>    at VSIXInstaller.App.TryAddSkuToValidSkuList(SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
> 22/06/2017 17:16:39 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
>    at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
>    at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    at VSIXInstaller.App.Initialize()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()

My VS version info is:

> Microsoft Visual Studio Enterprise 2017 
> Version 15.2 (26430.13) Release
> VisualStudio.15.Release/15.2.0+26430.13
> Microsoft .NET Framework
> Version 4.6.01590

**Comment by StefanKert** [comment]
Unfortunately I can not reproduce this issue, but I made some smalle changes to the packages config. You can grab the Build for this version (HERE)[https://ci.appveyor.com/api/buildjobs/ngfjbcw9tpksmm0b/artifacts/BuildVision%2Fbin%2FRelease%2FBuildVision.vsix]

**Comment by jbaute** [comment]
Great! This last build installs fine on vs2017. Thx!

**Comment by StefanKert** [comment]
Ok fine! Thanks for the information.
