### ISSUE TITLE
Use VSIXGallery for nightly/pre-release builds

### ISSUE THREAD

**Issue by willl** [StefanKert/BuildVision#25]
Firstly, really glad you took over the maintenance of BuildVision @StefanKert!
Glad this extension gets to live on :)

Just wanted to suggest looking at using [VSIXGallery](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VSIXGallery-nightlybuilds) to publish the pre-release builds of BuildVision. And then when you're ready, update the marketplace build.

If you're interested, here's a [guide](http://vsixgallery.com/guide/dev/) on adding BuildVision to VSIXGallery.

**Comment by StefanKert** [comment]
Thanks for the feedback. @TSchmiedlechner and  me really appreciate all your feedback on the work we are doing on this project. 

I really like the idea. I will take a look at it asap and I guess this is a real good solution for getting the Prereleases out to the users. Thanks! I´ll keep you updated on this.

**Comment by willl** [comment]
Cool. If you want to have a look at an example repo that's already doing this, take a look at https://github.com/madskristensen/WebEssentials2017 by @madskristensen (the author of VSIXGallery).

You'll see he has a link to VS marketplace, and also a link which indicates that users can grab the nightly/CI build from VSIXGallery.

**Comment by TSchmiedlechner** [comment]
Hey,
thanks for the idea, sounds nice! I manually uploaded the latest build with powershell and will add it to our AppVeyor script and the docs in the next days.
You can grab the build from http://vsixgallery.com/extension/837c3c3b-8382-4839-9c9a-807b758a929f/

**Comment by StefanKert** [comment]
If you´ve installed the plugin you´ve mentioned you also get a update notification. Awesome! Thanks for the advice @willl 

![image](https://user-images.githubusercontent.com/7176615/27556808-7b2367a4-5ab7-11e7-8b47-aa1c9743732b.png)

**Comment by willl** [comment]
Awesome :)

I'll close this issue then.
