### ISSUE TITLE
Please update version and credits.

### ISSUE THREAD

**Issue by igorushi** [StefanKert/BuildVision#26]
@StefanKert , I was unable to install a new 1.4.1.61 version on top of 1.5.0.0 from your old fork and had to uninstall :(
Also it looks like you need to update the credis in some hidden places :)
![image](https://user-images.githubusercontent.com/7131092/27540262-3dc1c42a-5a88-11e7-9e9d-c7e7cfd1e47d.png)

**Comment by StefanKert** [comment]
Sry for the inconvenience but since we accidentally bumped the version to 1.5.0 so we decided to go back to 1.4.x for the main repo. I hope this is not a big issue.

Regarding the version and credits: thanks for the tip. I will update them asap! Thanks
