### ISSUE TITLE
WiX projects results in error dialogs

### ISSUE THREAD

**Issue by JohnyWS** [StefanKert/BuildVision#27]
When building my solution which contains WiX projects, I am, for every WiX project I have, presented with this dialog when it starts building:

![image](https://user-images.githubusercontent.com/4435828/27833183-efafe33e-60d1-11e7-9911-6d6031070e14.png)

When the dialog is closed, the WiX project continues building correctly:

![image](https://user-images.githubusercontent.com/4435828/27833244-3483e050-60d2-11e7-8265-27cb87bccdc5.png)

Here is the full text in the dialog for search purposes:

---------------------------
BuildVision error
---------------------------
Unknown exception
Exception:
Specified cast is not valid.
StackTrace:
   at AlekseyNagovitsyn.BuildVision.Helpers.ProjectExtensions.GetOutputType(Project project)
Source:
BuildVision
TargetSite:
System.String GetOutputType(EnvDTE.Project)
BaseException:
System.InvalidCastException: Specified cast is not valid.
   at AlekseyNagovitsyn.BuildVision.Helpers.ProjectExtensions.GetOutputType(Project project)

**Comment by StefanKert** [comment]
What version of Buildvision have you installed? Are you using VS 2017 or a different one?

**Comment by JohnyWS** [comment]
Ah, my bad. I tried one of the forked versions, before you fixed the VS 2017 compatibility here. So either it was only that fork, or from before your restructuring of the code. It works with the latest version, thanks! :)

**Comment by JohnyWS** [comment]
For the record, this is the version I'm using now:
https://github.com/StefanKert/BuildVision/releases/tag/v1.4.0.57

Previously I've compiled my own version from the source code version uploaded here:
https://codeload.github.com/StefanKert/BuildVision/zip/master

**Comment by StefanKert** [comment]
Thanks dude! Glad that it worked out with the new build.
