### ISSUE TITLE
Market place publishment

### ISSUE THREAD

**Issue by guitarrapc** [StefanKert/BuildVision#29]
Hope this awesome VS2017 compatible package will be published on https://github.com/StefanKert/BuildVision 

Still I need to refer Release for latest releases or any updates.

**Comment by StefanKert** [comment]
We are planning to publish this extension asap, but we are still waiting for feedback, if everything works as expected and if we didn't introduce any new issues with our restructuring.

I will leave this issue opened untill we publish this extension. In the meantime you could use the Prereleased version that is provided via [VSIXGallery](http://vsixgallery.com/extension/837c3c3b-8382-4839-9c9a-807b758a929f/)

**Comment by StefanKert** [comment]
@guitarrapc since we succeeded migrating the Marketplace account I will try to get a working version to the marketplace until the end of this week. Stay tuned for updates!

**Comment by guitarrapc** [comment]
Awesome!!!! What a great news!

**Comment by StefanKert** [comment]
Partytime ;)!!!

![image](https://user-images.githubusercontent.com/7176615/29190718-6f247c2c-7e1b-11e7-900f-5016e654b52a.png)
