### ISSUE TITLE
VS 2017 Crash Report

### ISSUE THREAD

**Issue by NickCraver** [StefanKert/BuildVision#30]
Just found a crash for VS in the logs, stack here:

```
Unknown exception&#x000D;&#x000A;Exception:&#x000D;&#x000A;The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))&#x000D;&#x000A;StackTrace:&#x000D;&#x000A;
   at EnvDTE.ObjectExtenders.GetExtenderNames(String ExtenderCATID, Object ExtendeeObject)&#x000D;&#x000A;
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.get_ExtenderNames()&#x000D;&#x000A;
   at BuildVision.Helpers.ProjectExtensions.GetExtenderNames(Project project)&#x000D;&#x000A;Source:&#x000D;&#x000A;&#x000D;&#x000A;TargetSite:&#x000D;&#x000A;

System.Object GetExtenderNames(System.String, System.Object)&#x000D;&#x000A;BaseException:&#x000D;&#x000A;System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))&#x000D;&#x000A;
   at EnvDTE.ObjectExtenders.GetExtenderNames(String ExtenderCATID, Object ExtendeeObject)&#x000D;&#x000A;
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.get_ExtenderNames()&#x000D;&#x000A;
   at BuildVision.Helpers.ProjectExtensions.GetExtenderNames(Project project)
```

Hopefully that path makes some sense - VS 2017 Preview 7 in play. 

BuildVision Version: 1.4.1.61

**Comment by davkean** [comment]
Two bugs here that I can see;

1) we're not implementing IExtenderCATIDProvider - so the CATID that CPS is to ObjectExtenders.GetExtenderNames is very likely null.

2) CPS shouldn't be calling ObjectExtenders.GetExtenderNames if there's no IExtenderCATIDProvider.

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2686

**Comment by davkean** [comment]
This is our bug, feel free to close this one or leave it open if you want to work around it.

**Comment by StefanKert** [comment]
Thanks for the report Nick! And also thanks to you for the very very fast info on this @davkean and the reference to the issue. 

Anyway, I will take a look at this asap and try to find a workaround to fix it for the current preview.

**Comment by StefanKert** [comment]
After taking a closer look at this I think it would make no sense to fix this now. @NickCraver does this error result in a crash of for you? Because this error should be handled:

```
        public static string GetExtenderNames(this Project project)
        {
            try
            {
                var extenderNames = (object[])project.ExtenderNames;
                if (extenderNames == null || extenderNames.Length == 0)
                    return Resources.GridCellNoneText;

                return string.Join("; ", extenderNames);
            }
            catch (Exception ex)
            {
                ex.TraceUnknownException();
                return Resources.GridCellNAText;
            }
        }
```

I´ve also tested it with Preview 7 and it doesn´t crash my VS. Please let me know if this results in a crash of VS for you. If so we need to perform further action on this. Otherwise I will leave this issue open until 
 dotnet/project-system#2686 is fixed.

**Comment by NickCraver** [comment]
Thanks guys, closing this out since the root is tracked elsewhere, no need to clutter up here!
