### ISSUE TITLE
CreateInstance failed - VisualStudio 2015

### ISSUE THREAD

**Issue by guteksan** [StefanKert/BuildVision#34]
Today BuildVision simply didn't load when I started Visual Studio 2015. It has been installed 1 or 2 months ago, no other update or extension was installed on Visual Studio.  An error message was displayed suggesting to look at Visual Studio ActivityLog.xml file. There I found following entries:

```
  <entry>
    <record>582</record>
    <time>2017/08/11 13:15:48.148</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [BuildVisionPackage]</description>
    <guid>{837C3C3B-8382-4839-9C9A-807B758A929F}</guid>
  </entry>
  <entry>
    <record>583</record>
    <time>2017/08/11 13:15:48.163</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [BuildVisionPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{837C3C3B-8382-4839-9C9A-807B758A929F}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>
```
I tried to restart Visual Studio, restart PC, uninstall BuildVision and install again, all in vain. Could it be that Visual Studio has automatically updated to v2.0 that has just been released and it is broken?

**Comment by StefanKert** [comment]
Can you send me some details on the installed version? Are you using the current release?

**Comment by CharlEsterhuizen** [comment]
I have the same issue as Guteksan.  Same error.
I un-installed /re-installed ,Clean registry with no luck.
I have even tried to install v1.4.1.61 and that gave me the same error. Been using BuildVision for a very long time without any issues. It started after I manually upgraded to V2.0.0.92

**Comment by CharlEsterhuizen** [comment]
I have the same issue as Guteksan.  Same error.
I un-installed /re-installed ,Clean registry with no luck.
I have even tried to install v1.4.1.61 and that gave me the same error. Been using BuildVision for a very long time without any issues. It started after I manually upgraded to V2.0.0.92
Edit : The error pops up as soon as I open a solution. not when VS starts

**Comment by StefanKert** [comment]
Ok. Under invastigation. Will provide an Update asap!

**Comment by StefanKert** [comment]
The thing is, that we've upgraded a package to a newer version and installed this via nuget. It looks like these packages got not copied to the output dir and since this package is integrated in vs 2017 only this causes issues with vs 2013, vs 2015. i will provide an update asap but I am busy right now. Will get back to you if I fixed the bug. Sorry for the inconvenience!

**Comment by CharlEsterhuizen** [comment]
No worries, Knocking of for the weekend in a few mins. It will be tough but I think I can do a few compiles
without it. :)

**Comment by guteksan** [comment]
Hi,
Unfortunately, I left work already so won't be able to provide more info till Monday. I did not update BuildVision manually, so I suppose it auto-updated after new version had been released. And when I tried reinstalling, the version was V2.0.0.92. Everything was performed via "Updates and Extensions" in Visual Studio. Apparently, every user with VS lower than 2017 may be affected through this auto-update...

**Comment by StefanKert** [comment]
Hey guys. Good news! I found the issue and pushed a Prerelease. I´ve tested it with Visual Studio 2013, 2015 and 2017, but I would really appreciate it if someone of you could verify that this bug is fixed. The .vsix file can be found here: [https://github.com/StefanKert/BuildVision/releases/tag/v2.0.1](https://github.com/StefanKert/BuildVision/releases/tag/v2.0.1)

Please let me know if this is working for you. If everything is fine I will push this release to the marketplace. 

Thanks guys for reporting this and also thanks for verifying that this is working now <3

Have a nice weekend!

**Comment by codeworrier** [comment]
Prerelease 2.0.1 now properly loads on VS 2015 and 2013, Win7 SP1 x64 ... nice!

**Comment by StefanKert** [comment]
Awesome :) Thanks for your feedback @codeworrier! 

 I'll see if i can come up with a push to the marketplace today!

**Comment by StefanKert** [comment]
Release 2.0.1 Is out now! Sorry for the inconvenience :) Should be working now with VS 2013 and VS 2015. 

![image](https://user-images.githubusercontent.com/7176615/29248665-c8bb1cf6-801d-11e7-992c-06dcbb1cc69c.png)

If you still have a problem with this reopen, I will close this for now.
If you got other feedback, feature requests or bugs please create an issue and let us know, we really appreciate any feedback :)

**Comment by guteksan** [comment]
Just to confirm, version 2.0.1.98 has automatically updated from the online extensions repository and it is working. Meanwhile, some default settings, like showing buildvision window and showing progress on the taskbar, have changed, but I managed to find them and restore. Thank you for quick handling of this issue.

**Comment by StefanKert** [comment]
@guteksan sweet! Thanks for the feedback. Could you please create another issue with this problem, so that we can verify if this is indeed or a bug. Thanks!!

**Comment by guteksan** [comment]
I don't really consider it a true bug, rather an inconvenience. But if it helps you to improve the plugin, I can create another issue.

**Comment by StefanKert** [comment]
@guteksan we really want to sort out every little issue. In fact, this could also be a design decision we´ve probably made. Just want to keep track of this and maybe start a discussion if this fits the needs of the end users or not :)

**Comment by markbrents** [comment]
Thanks for the quick fix. You don't realize how valuable BuildVision is until you don't have it

**Comment by StefanKert** [comment]
@markbrents glad it worked out :) if you got any further feedback or wishes please create an issue :) really appreciate any feedback!
