### ISSUE TITLE
After upgrading to 2.0.1.98, the default settings have changes

### ISSUE THREAD

**Issue by guteksan** [StefanKert/BuildVision#38]
For versions 1.x of BuildVision, the default settings were:
- _Display build progress on Windows Taskbar_ was ON in General Options 
- _State on build begin_ was [Show window] in Tool Window options

After auto-update to 2.0.0.92, the plugin was unavailable
After another auto-update to a fixed version 2.0.1.98, the default settings have changed:
- _Display build progress on Window Taskbar_ checkbox was OFF
- _State on build begin_ was [Don't change window state]

In consequence, experience of an unaware user may be that the plugin is not working (BuildVision window is not visible when the build starts), although in fact it is working, while only the settings have changed.

**Comment by StefanKert** [comment]
Thanks for reporting this! I will take a look and get back to you if i got some details!
