### ISSUE TITLE
After updating to latest BuildVision, most of my projects fail to build, rebuild and clean

### ISSUE THREAD

**Issue by hilbert-tan** [StefanKert/BuildVision#39]
After updating to 2.0.1.98, i can't build, rebuild or clean my projects. They just keep saying "skipped", has anyone seen the same thing?

**Comment by StefanKert** [comment]
Thanks for the report. Haven't had this issue yet. Can you provide further information? For example Visual Studio version, is this only for specific builds? Does this only happen sometimes or always. Can you find any issues in the ActivityLog? Thanks in advance

**Comment by hilbert-tan** [comment]
Sorry for the false alarm, it was another extension that i installed caused this problem, i will close this ticket. And thanks so much for the quick fix last week.

**Comment by StefanKert** [comment]
Great :) thanks for the clarification!
