### ISSUE TITLE
Crash when using SSIS

### ISSUE THREAD

**Issue by LSMetag** [StefanKert/BuildVision#51]
Hi ! 

First, I really love your product. But It makes Visual Studio crash each time you try to run a SSIS package.
Visual hangs until you closes it.

So you can't use SSIS if BuildVision extension is enabled. I hope you'll be able to fix that.

Cheers

**Comment by StefanKert** [comment]
Hey there!

Thanks a lot for the kind words and also thank you for taking the time to posting this directly to GitHub :)

Sorry to hear that this is happening for you. Is it possible to get more details? Do you see anything in the Activity Log? Do you have a screenshot that shows your VS instance during the crash? Also can you please provide some more details on SSIS. I haven´t worked with SSIS within Visual Studio yet so it would be great to get an example package if you can provide one.

I assume that you are running on the latest version of BuildVision, but just to assure that this is true please let me know which version you are using.

Cheers :)

**Comment by LSMetag** [comment]
![executing first task](https://user-images.githubusercontent.com/7227332/32216041-25e57ae0-be24-11e7-96a1-0e9f40cee00f.png)


When I do "right click => execute" on the first task, the EDI becomes completely unresponsive.

Here is the request of the first SQL Task that removes every table in a database:

```
EXEC sp_MSForEachTable 'DISABLE TRIGGER ALL ON ?'
GO
EXEC sp_MSForEachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'
GO
EXEC sp_MSForEachTable 'DELETE FROM ?'
GO
EXEC sp_MSForEachTable 'ALTER TABLE ? CHECK CONSTRAINT ALL'
GO
EXEC sp_MSForEachTable 'ENABLE TRIGGER ALL ON ?'

GO
```

The issue is SSIS has its own compiler/builder and there may have a conflict.

Here is the log (I had to remove .xml extension to attach it here)

[Activity.log](https://github.com/StefanKert/BuildVision/files/1430110/Activity.log)

Thank you for your attention !

Cheers

**Comment by StefanKert** [comment]
Thanks for the details! I was able to reproduce this bug and will take a look at it asap. Don´t know if I can fix it this week, but I will keep you up to date on the state of this.

**Comment by StefanKert** [comment]
Just to give you a quick update on this:

I already fixed the issue but I need to do further testing. The problem we´re facing is, that it is a Visual Studio Bug I can only find a Workaround. 

I will see if I can do further checks tomorrow so that I can pre-release 2.1.1 for you to test it. 

Cheers :)

**Comment by StefanKert** [comment]
As said yesterday I had the time to test it out today. I created a basic solution with a SSIS project and it worked out with the newest build. You can grab the artifacts here https://ci.appveyor.com/project/StefanKert/buildvision/build/2.1.1.144/artifacts

Please let me know if this workes out for you too and if you found any further issues. If everything is fine, I will push a new release. 

Thanks for your help!

**Comment by LSMetag** [comment]
Thank you for being so prompt to answer ! I can't test before monday (I took days off) because I only got SSIS at work. But I trust you. I'll tell you if I get other issues.

**Comment by StefanKert** [comment]
Great. No worries. Just let me know if you had time to check it out and if it worked. Thanks and have a nice day off :)

**Comment by LSMetag** [comment]
It's fixed with this build ! Thank you !

**Comment by StefanKert** [comment]
Great! Thanks for the info. Glad to hear that it is working out :). I will deploy a new version this week so that everyone can get this fix :)

Thanks for your help! If you got any further feedback, bugs or ideas please let me know!
