### ISSUE TITLE
Grouping by State Doesn't Update During the Build

### ISSUE THREAD

**Issue by eddieparker** [StefanKert/BuildVision#52]
- Visual Studio Version: 15.0.27004.2008
- BuildVision Version: 2.1.0.143 
- OS Version: Microsoft Windows NT 10.0.15063.0

Steps to Reproduce:

1. Right click on the header and say "group by state"
2. Issue a build

You'll notice that completed builds don't get tucked into "BuildDone":

![image](https://user-images.githubusercontent.com/1141487/33023416-f2fb3acc-cdbc-11e7-9d3d-2f46ce9ee52b.png)

**Comment by StefanKert** [comment]
Thanks for reporting this issue! I was able to reproduce this. Will get back to you if I fixed it.

**Comment by StefanKert** [comment]
Hey there! I´ve added the fix into the current build on AppVeyor. Is it possible for you to download it directly from there and tell me if it now works out for you? Here is the link: https://ci.appveyor.com/project/StefanKert/buildvision/build/2.1.1.150

Thanks!

**Comment by StefanKert** [comment]
@eddieparker did you find the time to check the mentioned build if this is working now? I plan to release this verison this week, so if this works for you we are good to go :)

**Comment by eddieparker** [comment]
Somehow I missed the original pings on this - apologies.  Yes, this appears
to be working as of my latest sync and test: thanks for taking a look at
this!

**Comment by StefanKert** [comment]
No worries :) ! Thanks for the reply. I am glad that it works now.
