### ISSUE TITLE
Elapsed build time does not handle a duration greater than an hour

### ISSUE THREAD

**Issue by SirNH** [StefanKert/BuildVision#55]
The elapsed build time at the top of the window will wrap around back to 00:00 after an hour.  I work on a VERY large project and I wanted to use BuildVision to help benchmark various build optimizations.

**Comment by StefanKert** [comment]
Hey there, 

I assume that you are talking about the time in the header:

![image](https://user-images.githubusercontent.com/7176615/34640799-efc77e94-f2f9-11e7-968d-ba12cea798de.png)

You can change this by going to

Tools -> Options... -> BuildVision -> Build Messages 

And then change the following field:

![image](https://user-images.githubusercontent.com/7176615/34640810-1772be68-f2fa-11e7-906e-9c02d15b5ac7.png)

If you want to display hours as well as minutes and seconds type in:

```
hh\:mm\:ss
```

The result will then look like this:

![image](https://user-images.githubusercontent.com/7176615/34640815-34d5d422-f2fa-11e7-8c2d-4a0a7995fa38.png)

**Comment by StefanKert** [comment]
Any news on this @SirNH?

**Comment by SirNH** [comment]
Yup, it's working!  Thanks for the advice!

------ Original Message ------

**Comment by StefanKert** [comment]
Great! Thanks for the really (!) fast reply :).
