### ISSUE TITLE
Feature Request: BuildOrder column values to match VS Build Ordinal, or add new column for VS project build ordinal position

### ISSUE THREAD

**Issue by rb126** [StefanKert/BuildVision#67]
Again - great extension, thanks!  I have noticed that the Visual Studio project index ("build ordinal number" in Output window) doesn't match the BuildOrder value in Build Vision.  Would it be possible to support another column that shows this build order (or add an option to exclude all "UpToDate" projects from numbering so I can hide UpToDate projects and get the numbers to match?  This would be handy so when something is building quite slowly as viewed in BuildVision I can check the number and quickly find it in the output window.

Examples:

(1)  They start off in sync:

![buildvision1](https://user-images.githubusercontent.com/7371821/44985784-75f9aa00-af79-11e8-9042-14943e667d3b.png)

![buildvision2](https://user-images.githubusercontent.com/7371821/44985792-7abe5e00-af79-11e8-938d-0164e3d90db5.png)

After a project or two has been skipped due to them being "UpToDate" they get out of step:

![buildvision3](https://user-images.githubusercontent.com/7371821/44985812-8e69c480-af79-11e8-91f4-c05522a0ba7c.png)

![buildvision4](https://user-images.githubusercontent.com/7371821/44985816-90cc1e80-af79-11e8-9469-1d2d2f74b94b.png)

So after a while they are way out and the numbers don't even remotely correspond.

![buildvision5](https://user-images.githubusercontent.com/7371821/44985834-a04b6780-af79-11e8-9f0a-35b5d1403534.png)

![buildvision6](https://user-images.githubusercontent.com/7371821/44985837-a4778500-af79-11e8-8306-8446ff583cbc.png)

If I hide UpToDate projects it doesn't help as the numbering is still the numbering for a full rebuild, even though I didn't do a full rebuild and many projects were skipped:

![buildvision7](https://user-images.githubusercontent.com/7371821/44985906-ed2f3e00-af79-11e8-978d-c2f92c7c33a6.png)

**Comment by StefanKert** [comment]
Good catch! 

This behaviour is mostly because the Build ordinal number is created during runtime and then cached. I need to do further investigation on this to see if we can get the Build No directly from VS.

So to me there are two questions here that need to be answerd:

1. Is it possible to sync the Number in BuildVision with the Number in the output?
2. What numbers should be taken if UpToDate Projects are hidden? 

As I mentioned earlier, I will take a look if I can answer the 1., but I am not quite sure what about 2. IMO there are several options. Maybe this can be solved by solving 1? So maybe we would fix the issue with the uptodate builds if we get the number from the output. But then again we would have to find a procedure how to handle shown uptodate builds.

**Comment by rb126** [comment]
I would be tempted to introduce a new column, to be honest, because numbers that include the "UpToDate" projects will never sync, because VS ignores those, but there might be times when you do want to see the full build order, which is what your current column provides.

**Comment by yannduran** [comment]
The main problem here for me is that when I select the _BuildOrder_ (#) column to sort by (no matter what the number actually  represents), the grid isn't sorted by that number during the build.

![image](https://user-images.githubusercontent.com/2031126/56857367-e5f8ec80-69af-11e9-8399-a86ab0e93ec8.png)

The numbers match up with the output seen in the Output window, so they are in fact the "build order", but the rows simply aren't sorted by it as the build progresses.

![image](https://user-images.githubusercontent.com/2031126/56857419-86e7a780-69b0-11e9-9254-a138921fe13b.png)

Maybe the build order "numbers" could be obtained from the dependency tree in advance? The "unchanged" projects could be filtered out. Then the rows could be sorted before being displayed. Just a thought. :-)

**Comment by StefanKert** [comment]
Closing as duplicated of #53
