### ISSUE TITLE
vs2019 warns about usage of deprecated APIs

### ISSUE THREAD

**Issue by Atrejoe** [StefanKert/BuildVision#72]
VS2019 Preview warns that BuildVision may not work with future versions:

![image](https://user-images.githubusercontent.com/585091/54443113-4b668600-4740-11e9-9d5b-9da33948cebf.png)

Using buildvision 2.2.0.4

**Comment by StefanKert** [comment]
Hi there,

thanks for the heads up. I am currently working on the VS2019 release. You can follow the process in #71. I hope that I can have a first pre release by the end of next week.

**Comment by willl** [comment]
Just an FYI - [VS 16.1 Preview 1 disables any extensions that are synchronously auto loaded](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#extensibility).
![image](https://user-images.githubusercontent.com/926823/56018173-b2c62480-5d44-11e9-9855-effd1f3a2857.png)

**Comment by StefanKert** [comment]
HI @willl ,

I just published a first draft of the new version to http://vsixgallery.com/extension/837c3c3b-8382-4839-9c9a-807b758a929f/

If you have time to check it let me know if it works for you or if you are facing any issues.

**Comment by willl** [comment]
Thank you @StefanKert. Installed it this morning and it seems great so far 👍

**Comment by Atrejoe** [comment]
Thanks a lot, this appears to work without warnings and has a nice 'preview' label ;)
One question: didn't the previous version allow expand the lines to display details of any build errors/warnings?

**Comment by StefanKert** [comment]
Hi  @Atrejoe,

yeah actually there is a bug in the current Preview that breaks the error stuff. I am currently working on it :). I will close this issue for now. If you are on the "beta feed" you will see the fix as soon as it is up :)
