### ISSUE TITLE
Elapsed Time Continues After Build Has Completed

### ISSUE THREAD

**Issue by yannduran** [StefanKert/BuildVision#75]
v3.0.0.90

![image](https://user-images.githubusercontent.com/2031126/56874835-f37da780-6a7f-11e9-9bcc-575a7365a280.png)

The elapsed time never stops counting

**Comment by yannduran** [comment]
This seems to have stopped now. Curiously, the version number remains v3.0.0.90 (weird).

But I do now end up with two sets of parentheses:

![image](https://user-images.githubusercontent.com/2031126/57574770-64f72600-7482-11e9-8b68-deda1b4d8979.png)

**Comment by savehansson** [comment]
I've seen this exact issue(s) too.

- Visual Studio Version: 16.0.29001.49
- BuildVision Version: 3.0.0.90 
- OS Version: Microsoft Windows NT 10.0.18362.0

Steps to Reproduce:

1. Don't know :(

After running some builds, (Ctrl+Shift+B), some with errors/warnings, some without, the elapsed time in the head doesn't stop after a build is completed. It just keeps ticking.

Workaround:

1. Restart VS (I think, at least I can't reproduce it after my latest restart).

If I find out how to reproduce, I'll get back to you.

**Comment by savehansson** [comment]
I managed to reproduce it. I just canceled a build (with the Cancel button in the BuildVision head). Elapsed time continues to count.
![image](https://user-images.githubusercontent.com/650548/59830539-2cc7ea80-9340-11e9-87a0-3ddacf92dcca.png)

**Comment by StefanKert** [comment]
This looks pretty weird. I am currently investigating, but didn´t have this problem yet. I´ll keep you posted as soon as I have a solution.

**Comment by StefanKert** [comment]
Hi folks!

sorry for the delay. As mentioned in #80 this should be solved in the latest pushed version (3.0.0-preview-1.96+2cf7960452). Maybe you could give it a try and let me know if it is working for you. Thanks!

**Comment by yannduran** [comment]
I can confirm that this doesn't seem to be happening in build 3.0.0.104.

**Comment by jzabroski** [comment]
@StefanKert Just a question... what is the versioning scheme for BuildVision?  I found this thread because I am on 3.0.0+e9e47924bc, but I can't infer from 3.0.0-preview-1.96+2cf7960452 whether my version is greater or less than that number.  I do know I built this computer in Amazon Workspaces in March, so in theory it should've come after 3.0.0-preview-1.96+2cf7960452 ?

**Comment by yannduran** [comment]
@jzabroski if you take a look in the _Extension Manager_, a more user-friendly version is displayed there.

I also currently have `v3.0.0+e9e47924bc` installed (& this appears in the tool window tab if you have it docked). 

![image](https://user-images.githubusercontent.com/2031126/85485023-48c53280-b60b-11ea-8827-5cc3bcbf391b.png)

In _Extension Manager_ it shows as `3.0.0.104.`.

![image](https://user-images.githubusercontent.com/2031126/85484798-e4a26e80-b60a-11ea-8e31-9233b505db21.png)

**Comment by jzabroski** [comment]
@yannduran It is still difficult to understand which one is greater.  Preview builds do not go on marketplace, so I am trying to understand the lineage of releases between official releases and previews.

**Comment by StefanKert** [comment]
Hi folks!

sorry for the delay and thanks to @yannduran for jumping in and answering :)

@jzabroski you are definetly right. The versioning is really confusing at the moment. The idea of these versions is based on Semantic Versioning and therefore it should follow the following approach:

Major.Minor.Patch[-Prerelease]+gitHash 

So the actual release is 3.0.0+e9e47924bc
If a prerelease flag is added like in 3.0.0-preview-1.96+2cf7960452 it is prior the actual release. The prerelease flag is only used in versions that can be installed manually or through the various feeds. 

For the future I think it makes sense to remove the git Hash from the Productversion to make things mor cleary:

3.0.0
3.0.1-preview.1
3.0.1-preview.2
3.0.1
3.1.0-preview.1
...

**Comment by jzabroski** [comment]
@StefanKert Thank you.  I love this tool (and the name of it), by the way.  People like you, with an eye for simplicity, are **force multipliers**.
