### ISSUE TITLE
Sorting on start time does not work

### ISSUE THREAD

**Issue by manu-st** [StefanKert/BuildVision#78]
I'm using 3.0.0.90 from the VSIX feed with VS 2019. It doesn't seem that sorting is working properly during a build as shown here:

![image](https://user-images.githubusercontent.com/13194660/58356672-fd02f100-7e2c-11e9-80c7-564d99c424af.png)

If I click the column header it will eventually sort. It is as if during the build the sorting criteria was not taken into account at all.

**Comment by StefanKert** [comment]
Thanks for bringing this up. The latest version (3.0.0.91) should now order correctly.
