### ISSUE TITLE
LoadException with newest VS 2019 16.2.0 Preview 3.0

### ISSUE THREAD

**Issue by Stelzi79** [StefanKert/BuildVision#79]
## Visual Studio Version
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.2.0 Preview 3.0

## BuildVision version
3.0.0.90 (the version from the VSIX gallery dev-build feed)

## Steps
- open VS with installed and activated BuildVision Extension

or

- manually open the BuildVision window

## Expected
- open without any exceptions

## Actual
- VS error that Extension couldn't be loaded ![Screenshot_1](https://user-images.githubusercontent.com/969932/60296834-3c8a9480-9927-11e9-873f-6d4b51cebc4f.jpg)

## ErrorEntry from ActivityLog.xml
> CreateInstance failed for package [BuildVisionPackage]Source: &apos;mscorlib&apos; Description: Exception has been thrown by the target of an invocation.&#x000D;&#x000A;System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.MissingMethodException: Method not found: &apos;Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1&lt;Int64&gt;, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1&lt;System.TimeSpan&gt;, Serilog.RollingInterval, Boolean, System.Nullable`1&lt;Int32&gt;, System.Text.Encoding)&apos;.&#x000D;&#x000A;   at BuildVision.Common.Logging.LogManager.CreateLogger()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at BuildVision.Common.Logging.LogManager.ForContext(Type type)&#x000D;&#x000A;   at BuildVision.Common.Logging.LogManager.ForContext[T]()&#x000D;&#x000A;   at BuildVision.Core.BuildVisionPackage..ctor()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.MissingMethodException: Method not found: &apos;Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1&lt;Int64&gt;, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1&lt;System.TimeSpan&gt;, Serilog.RollingInterval, Boolean, System.Nullable`1&lt;Int32&gt;, System.Text.Encoding)&apos;.&#x000D;&#x000A;   at BuildVision.Common.Logging.LogManager.CreateLogger()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at BuildVision.Common.Logging.LogManager.ForContext(Type type)&#x000D;&#x000A;   at BuildVision.Common.Logging.LogManager.ForContext[T]()&#x000D;&#x000A;   at BuildVision.Core.BuildVisionPackage..ctor()

**Comment by Stelzi79** [comment]
Seems to be some problem with Serilog.

**Comment by StefanKert** [comment]
Thanks for bring this up. I had no time yet to install the latest preview but will do so asap. I´ll let you know as soon as I have more information.

**Comment by StefanKert** [comment]
Hi  @Stelzi79 ,
I just checked with the latest preview and it seems like it is working. Is this issue resolved for you as well?

**Comment by Stelzi79** [comment]
Well now it is somehow working again for me. Maybe a VS Preview or net core preview issue on my end and I worked with Blazor quiet a bit. I will report it if I have that problem again.

**Comment by StefanKert** [comment]
Would it be ok for you if I close this issue and you reopne it as soon as this issue comes back?

**Comment by Stelzi79** [comment]
Yes that would be OK. I will reopen if it comes back.
