### ISSUE TITLE
Build slow down with this extension

### ISSUE THREAD

**Issue by duszekmestre** [StefanKert/BuildVision#8]
Normally my project builds in less than one minute. But with Build Vision extension it works over four minutes. Please make no impact on build time with this tool.

**Comment by pavelhritonenko** [comment]
+1

It's takes about 2.5 minutes to check my solution is up to date. When I switch from BuildVision window to Build Output window (they are in the same dock) it takes about 4.5sec (~180 projects).

So it's unusable in my case.

**Comment by brobichaud** [comment]
Yeah I too was disappointed to see this. I love the extension and the info it shows but the build time hit is too expensive. My solution went from 45 secs to 75 secs. May not sound like much off hand but that is 166% of the original time.

**Comment by drubbo** [comment]
+1. We have a solution with ~300 projects and while building it with this extension active, the whole Visual Studio UI becomes unresponsive.

**Comment by StefanKert** [comment]
@drubbo thanks for adding this here. Like @Tschmiedlechner mentioned in #35 we are already working on improving the performane for BuildVision. If we come up with something it would be cool if we can ping you for beta testing the improvements, to figure out if this works for you. Anyway I really appreciate your feedback!

**Comment by JohnyWS** [comment]
You can ping me as well @StefanKert. We have several developers who has changed over to R# build instead, because of the slow down in build speed.

**Comment by StefanKert** [comment]
@JohnyWS awesome! Thanks dude. I will see if i can get some improvements in until the next milestone. Has this issue been in the past versions too or is it only 2.x.x?

**Comment by drubbo** [comment]
@StefanKert sure np

**Comment by JohnyWS** [comment]
That we don't know unfortunately, unless you can compare with VS 2015 speeds before VS 2017 even was out, because that's when we last had it rolled out to many users, and none were complaining about it at that time.

**Comment by kevinboss** [comment]
+1 . We have a projekt with 500+ Project, buildtime is well above 30 minutes...which isn't really something I can live with...

**Comment by StefanKert** [comment]
I drafted a prerelease that has some performance improvements included. You can grab it under [https://github.com/StefanKert/BuildVision/releases/tag/v2.1.0-alpha-1](https://github.com/StefanKert/BuildVision/releases/tag/v2.1.0-alpha-1).

Would be great if some of you could check if this speeds up your build process. Please let me know!
Thanks in advance. Cheers

**Comment by JohnyWS** [comment]
I've sent it out to two of my teammates, and hope to know more in 3-4 days time.

**Comment by StefanKert** [comment]
@JohnyWS great! Looking forward to your response.

Anyway, I would really appreciate any further feedback  on this :)

**Comment by JohnyWS** [comment]
1st impressions: Massive improvement. :) VS does not hang nearly as much. 👍

**Comment by StefanKert** [comment]
Awesome! Thanks for the feedback. Sounds great :) I will see if I can find more bits that can be improved, but I am really glad that it seems like this fixes some issues :)


@drubbo @kevinboss is it possible for you to install the pre-release and give me some feedback on this? Thanks in advance!

**Comment by kevinboss** [comment]
@StefanKert 

I aborted after 20 Minutes and ~400 projects. The whole solution is 508 projects, I guess it would still be around 30 minutes overall.

**Comment by StefanKert** [comment]
@kevinboss thanks for the info.

How long does a build of your solution usually take?

**Comment by kevinboss** [comment]
@StefanKert Not more than 7-8 minutes if I make a complete re-build.

**Comment by StefanKert** [comment]
@kevinboss ok. This is of course unacceptable. Is this C++ or C#? I guess it is not an opensource project. The issue here is that it is really difficult to get a solution that is that big. If anyone knows an example that is  > 100 projects big please let me know.

**Comment by kevinboss** [comment]
@StefanKert It is a C# project, full-framework (4.5.2) and VS 2013, so no Roslyn. And yes, it is a closed source project.

We are currently upgrading to 2017 and 4.7, so maybe I can try it again when that is done.

**Comment by StefanKert** [comment]
@kevinboss gotcha. Thanks anyway for the feedback! Really appreciate it. I will try to generate a solution (>100) and see if I can find some bottlenecks. Really curious if this upgrade will improve the overall performance.

**Comment by StefanKert** [comment]
Seems like I found one of the major performance issues. I created a solution with 100 projects: 

| Run | No BuildVision | BuildVision 2.1 alpha 1 | BuildVision 2.1 aplha 2 |
| ------------- |:-------------:| -----:|-----:|
| 1      | 00:00:29 | 00:01:50| 00:00:34 |
| 2    | 00:00:28 |  00:01:41 | 00:00:30 |
| 3 | 00:00:31      |    00:01:49 | 00:00:31 |


So you can see that we got a major improvement here ( nearly x4). I have to admit that it is possible that the performance win for most of you guys will not be that big, but I think you will gain a pretty big improvement. 

Again I´d be really glad if I can get feedback on this @kevinboss, @JohnyWS, @drubbo. I am especially interested in the performance gain for Solutions that are > 100 projects. So thank you all in advance!

Btw you can grab the release under https://github.com/StefanKert/BuildVision/releases/tag/v2.1.0-alpha-2

Again I wanna thank you all for the feedback and for helping get BuildVision faster :)

**Comment by drubbo** [comment]
yep I'll do that as soon _as possible_.

**Comment by drubbo** [comment]
Looking good so far, well done. I'll benchmark it on a monster solution during the weekend.

**Comment by kevinboss** [comment]
@StefanKert 

I tried the 2.1 alpha 2 Build and it was done in 5:06, that is really great. I can't really see a difference between the addon and no addon anymore.

**Comment by StefanKert** [comment]
@drubbo thanks for the feedback! Great to hear that it is working for you :). Hope this will also work properly with your monster solution. 

@kevinboss awesome!! Thank you so much for the feedback you gave on this. Really helped me getting this thing faster :) 

Really glad that this worked out. Would be great to get further feedback from some of you guys ( @duszekmestre, @pavelhritonenko, @brobichaud)

@JohnyWS since alpha-1 already worked out for you I think this wouldn´t have so much impact on you but anyway if you already gave it to some folks of your team or tried it on your own I really like to know if it is even faster.

Thanks guys!

**Comment by JohnyWS** [comment]
@StefanKert I had full days mapped out with meetings and final work to do before the current vacation (this week), so sadly, I did not get around to getting more feedback, so mine will be a bit late to the party. We have 100+ projects too though, so I'll let you know when I have some numbers. :) - judging from the other feedback, it does already look like it's worth using the current iteration though. :) Nice work!

**Comment by StefanKert** [comment]
@JohnyWS no worries! If you tested it please let me know if this worked for you too. Thanks!

**Comment by StefanKert** [comment]
Since most of you gave the feedback that the current alpha release fixes this issue I will close this for now. 

@JohnyWS still curious if this fixes your performance issue too (or further improves performance for you since the first alpha already fixed most of the issues for you)

If there are any performance issues in the future please create a separate issue. Thank you all for the great work and the great feedback, especially @JohnyWS , @kevinboss and @drubbo.
