### ISSUE TITLE
Solution build time is wrong

### ISSUE THREAD

**Issue by amirgon** [StefanKert/BuildVision#80]
![image](https://user-images.githubusercontent.com/11742638/65589742-35a90780-df92-11e9-8642-52beef6592ab.png)

Total solution build time is **not** 20:24 as displayed in the header.
The first project started on 06:32:19, and the solution completed on 07:52:41, so the true solution build time **should be 1:20:22**

 - BuildVision 2.1.1.157 (installed from the Visual Studio Gallery in Extensions and Updates)
 - Microsoft Visual Studio Professional 2015, Version 14.0.25431.01 Update 3
 - Building a C++ solution

**Comment by StefanKert** [comment]
Hi!

Thanks for the heads up. I just pushed a new version (3.0.0-preview-1.96+2cf7960452) which should solve this issue. You should be able to update it if you configure VSIX Gallery in visual studio. Please let me know if this fixed your issue. Also it should lower the build time and cpu usage.

**Comment by StefanKert** [comment]
Closing this since it should be fixed :) please reopen / open another issue if this still happens
