### ISSUE TITLE
Fill projects list on build begin does not work

### ISSUE THREAD

**Issue by pyrocumulus** [StefanKert/BuildVision#81]
In the preview version for 2019, it appears the option "Fill projects list on build begin" isn't working anymore. I tried setting the option and restarting VS but to no avail. The list still only populates by the projects it has built, instead of preparing the whole list.

Not a major problem obviously but I like seeing the build in advance (including up-to-date projects) so it's a pretty useful function for me.

Build vision version: 3.0.0-preview-1.99+6ae7b4a6ab
Visual Studio 2019 version: 16.2.5

**Comment by StefanKert** [comment]
Hi @pyrocumulus 

I just checked the version that you are using and for me it is working, I can even switch the option during the build and it shows all projects.

Are you doing a full build of the solution or just a single project?

**Comment by pyrocumulus** [comment]
Full solution (re)build and single project (re)build both have the same issue. They clear the project list at the beginning and then add to it, one built project at a time. I do not have the 'Hide up to date targets' option on by the way. I tried switching the option on and off again, even restarting VS between changes; nothing appears to change in the behaviour. Also I've noticed that the last project that's started building is shown twice (while building and afterwards still), don't know if that's related though.

 I can try completely uninstalling the extension, maybe that helps.

**Comment by pyrocumulus** [comment]
I think I've found the reason for this problem. I have a solution with some of the projects in an unloaded state and that seems to cause this issue. If I load all the projects in the solution, then the project list shows all the projects as well.

**Comment by StefanKert** [comment]
Thanks for the update :). That sounds reasonable. Would you expect BuildVision to show also the unloaded projects? Because since they are not really builded if they are unloaded I would not expect them to be there.

**Comment by pyrocumulus** [comment]
I understand why they would be omitted from the build list. Something could
be said for adding them in an 'Unloaded' build state, but for developers
with large solutions that might be impractical.

However, just to be clear: my problem is not with the missing *unloaded*
projects. It's when I have an unloaded project, the rest of the loaded
projects *also* do not fill the project list on build start. The complete
setting appears to stop working.

Op za 30 nov. 2019 07:28 schreef Stefan Kert <notifications@github.com>:

**Comment by StefanKert** [comment]
Hi @pyrocumulus,

thanks for the clarification. I´ll try to reproduce this and fix it in the next preview :) thanks a lot!
