### ISSUE TITLE
BuildVision 3 does not load on VisualStudio 2015

### ISSUE THREAD

**Issue by FilRip** [StefanKert/BuildVision#88]
Hello,

Since BuildVision is now on version 3, sometimes, VisualStudio launch but freeze when launching by double click on a .sln file. But load with success when i launch VisualStudio then load the sln by select it in VS menu "File/Open/projet or solution"

So i have try to uninstall BuildVision, restart VS then reinstall BuildVision and restart VS.

I go to "View/Others Windows/BuildVision" but i have this error : the package BuildVisionPackage can't be correctly loaded (in french, so this is my English translation). "The problem can be due to modification of the configuration, or because of install another extension. For more information, check ...ActivityLog.xml"

And so, there is the entry in ActivityLog.xml :
"Begin package load [BuildVisionPackage]"
"CreateInstance failed for package [BuildVisionPackage]Source: 'mscorlib' Description: Une exception a été levée par la cible d'un appel. System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.**MissingMethodException**: Méthode introuvable : 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding)'.à BuildVision.Common.Logging.LogManager.CreateLogger()à System.Lazy`1.CreateValue()à System.Lazy`1.LazyInitValue()à System.Lazy`1.get_Value()à BuildVision.Common.Logging.LogManager.ForContext(Type type)à BuildVision.Common.Logging.LogManager.ForContext[T]()à BuildVision.Core.BuildVisionPackage..ctor() --- Fin de la trace de la pile d'exception interne --- à System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)à System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)à System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)à System.Activator.CreateInstance(Type type, Boolean nonPublic)à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)à System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)à System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.MissingMethodException: Méthode introuvable : 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding)'.à BuildVision.Common.Logging.LogManager.CreateLogger()à System.Lazy`1.CreateValue()à System.Lazy`1.LazyInitValue()à System.Lazy`1.get_Value()à BuildVision.Common.Logging.LogManager.ForContext(Type type)à BuildVision.Common.Logging.LogManager.ForContext[T]()à BuildVision.Core.BuildVisionPackage..ctor()"

Of course, restart computer and/or VisualStudio does nothing. And i had no problem in v2.x before.

Thank you for your help.

------------------------------------
My VS : VisualStudio Pro 2015
Version 14.0.25431.01 Update 3
Others extensions installed (dont know if it's important) : 
- AutoDeploy
- Microsoft Child Process Debugging
- Color Theme Designer
- GitExtensions
- Smart Command Line Arguments
- TortoiseGit Toolbar
- Viasfora

**Comment by PeterJeff** [comment]
I am also having this problem with the same version

**Comment by sstefan1** [comment]
Can confirm. VS2015 hangs for me as well.

**Comment by StefanKert** [comment]
Hey folks,

thanks for raising this. I will need to investigate this further. I´ll let you know as soon as there is an update available.

**Comment by bdbvb** [comment]
Just an FYI, I'm getting this same issue with Visual Studio 2019 (16.4.6), and can't (usually) get BuildVision to come up, though Visual Studio itself as well as other extensions are OK. The activity log message is:

"CreateInstance failed for package [BuildVisionPackage]Source: 'mscorlib' Description: Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding)'.   at BuildVision.Common.Logging.LogManager.CreateLogger()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at BuildVision.Common.Logging.LogManager.ForContext(Type type)   at BuildVision.Common.Logging.LogManager.ForContext[T]()   at BuildVision.Core.BuildVisionPackage..ctor()   --- End of inner exception stack trace ---   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)   at System.Activator.CreateInstance(Type type, Boolean nonPublic)   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding)'.   at BuildVision.Common.Logging.LogManager.CreateLogger()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at BuildVision.Common.Logging.LogManager.ForContext(Type type)   at BuildVision.Common.Logging.LogManager.ForContext[T]()   at BuildVision.Core.BuildVisionPackage..ctor()
--"

**Comment by StefanKert** [comment]
This should be fixed with the new version 3.0.1. If you are still seeing issues please let me know :)

Thank you a lot for your patience and sorry for the very long time taken for this fix.
