### ISSUE TITLE
Sorting by Build Order has gone wrong in V3

### ISSUE THREAD

**Issue by rb126** [StefanKert/BuildVision#89]
Hi Stefan - I've noticed sorting by build order seems to have gone wrong since the 3.0 update four days ago.  Projects seem to be appearing at random in the grid view, and if I sort by '#' to fix it and get them in order during a build then new projects to start building then just start popping up again in the middle of all the already-built projects.  Is this just me, or has there been a regression?  Thanks!

**Comment by rb126** [comment]
Here's an example - the build order was seemingly random, so I clicked on the '#' column to sort in order around the time project number 74 was building, and you can see that later projects just scattered all over the place after that:

![image](https://user-images.githubusercontent.com/7371821/75439856-7eeef000-5952-11ea-8463-5eefc804e12c.png)

**Comment by pentp** [comment]
I'm having the same issue with Build Order column sorting and also Build start time column.

**Comment by rb126** [comment]
Any idea when 3.0.1 with a fix for this might be available?  I've just now rolled back to 2.1.1 and projects are now added to the list in the correct order again.  This was one of the main reasons I used BuildVision - so I could easily see the progress of my build, and this is not possible if the projects are added throughout the build scattered at random somewhere in the list.

**Comment by victornovik** [comment]
Dear Stefan,
Could you please fix up this regression bug?
It is really annoying and people have to roll back to the old versions of your useful plugin.

**Comment by StefanKert** [comment]
Hi @victornovik ,

Thanks for bringing this up again :)

Because of other projects, I don´t have a lot of time for opensource lately, so that is why feature development / bugfixing takes very long. I know that this is not very satisfying and  I am really sorry.

I´ll try to provide a fix this week :)

**Comment by rb126** [comment]
Many thanks, Stefan - I look forward to giving this a go.

**Comment by StefanKert** [comment]
Hi @rb126,

![image](https://user-images.githubusercontent.com/7176615/87790869-8e0f0580-c841-11ea-86f8-004ddc76ade6.png)

Looks good now :)

if you want to give it a shot you can grab the artifact of the latest build https://dev.azure.com/stefankert/_apis/resources/Containers/2834886/VsixGallery?itemPath=VsixGallery%2FBuildVision.vsix

I am happy for any feedback :). I will try to push a release 3.0.1 today with additional fixes.

**Comment by rb126** [comment]
Thanks, Stefan, but if 3.0.1 is out later today I'll grab that with the "additional fixes" :-)  Thanks for fixing this one though!

**Comment by StefanKert** [comment]
@rb126 @victornovik the new version can be downloaded from the marketplace now 😃 and orderin should work now

**Comment by victornovik** [comment]
> @rb126 @victornovik the new version can be downloaded from the marketplace now 😃 and orderin should work now

Hi Stefan

It works now in 3.0.1!
Great job!
I really appreciate your fix.
