### ISSUE TITLE
Selected columns not persisting

### ISSUE THREAD

**Issue by martinsmith1968** [StefanKert/BuildVision#91]
If I make changes to the visible columns, when I close and restart Visual Studio the default columns are shown again.

E.g.
Hide Build Finish Time, Show Framework and Output
Restart Visual Studio
Build Finish Time is visible, Framework and Output are not

Due to the types of project I'm building in VS I have to run VS as administrator - maybe that is having an effect ?

Thanks

**Comment by daniel-schmidt** [comment]
I can confirm this problem, running VS 2019 not as an administrator.

**Comment by StefanKert** [comment]
Hi folks!

thanks for the heads up. I was able to reproduce this and will try to fix it in the next days :). I´ll let you know as soon as the fix is pushed.
