### ISSUE TITLE
Columns not resizing according to their headers

### ISSUE THREAD

**Issue by jdavis-leasehawk** [StefanKert/BuildVision#94]
- Visual Studio Version: 16.0.29931.138
- BuildVision Version: 3.0.0.104 
- OS Version: Microsoft Windows NT 10.0.18363.0

Steps to Reproduce:

1. i don't know what I'm doing special, I have a .net standard class lib project and this is what I see, and if I try resizing the column headers nothing happens
2.
![image](https://user-images.githubusercontent.com/59490349/79809388-2a9a3800-8325-11ea-9d49-6ea275502675.png)

**Comment by StefanKert** [comment]
Can you try a minimal project that reproduces this issue and upload it? I am currently not able to reproduce this on my local machine. One thing that is maybe worth mentioning is, that the errorlist is a own component, so it is not really resizable at the moment

**Comment by StefanKert** [comment]
This should be corrected in v3.0.1 which is going to go online today. If you are still seeing these problems please reopen or create another issue.
