### ISSUE TITLE
v3.0.0.104 still has a 'Preview' marker in the header

### ISSUE THREAD

**Issue by yannduran** [StefanKert/BuildVision#95]
If I understand correctly, v3.0.0.104 is no longer a _preview_ release? There is still a _preview_ marker in the header:

![image](https://user-images.githubusercontent.com/2031126/79861595-fc495500-8417-11ea-961b-8b6d41cb9823.png)

**Comment by StefanKert** [comment]
Indeed! Looks like there is something weird happening in the build pipe. I´ll check that and let you know as soon as it is fixed. Thanks for the heads up

**Comment by yannduran** [comment]
Kein problem! Anytime.

**Comment by yannduran** [comment]
I think I found why the **_Preview_** marker appears.

In line 43 of `ControlView.xaml` there's a `Border` element whose visibility's being bound to `PreviewVersion` in `BuildVisionPaneViewModel`.

![image](https://user-images.githubusercontent.com/2031126/85920435-28210500-b8b7-11ea-838d-1b6eb8d5ce0a.png)

It's possible that the extension isn't being published using the `Marketplace` configuration, but AFAIK you can't bind to a constant in a viewmodel, only to a property.

HTH
