### ISSUE TITLE
Release Note link in the VS Marketplace Is Incorrect

### ISSUE THREAD

**Issue by yannduran** [StefanKert/BuildVision#96]
Under the _Related Links_ heading in the [marketplace page](https://marketplace.visualstudio.com/items?itemName=stefankert.BuildVision), the _Release Notes_ link takes you to:
> https://github.com/StefanKert/BuildVision/releases/tag/v2.0.0

instead of:

> https://github.com/StefanKert/BuildVision/releases/tag/v3.0.0

**Comment by StefanKert** [comment]
Thanks! Fixed :)
